title: Adaeze Okeukwu-Ogbonnaya
logo: /assets/img/headshot_circle.png
#description:
#show_downloads: true
theme: jekyll-theme-minimal
social_links: true
linkedin: 'https://linkedin.com/in/adaezeokeukwu'
google_scholar: 'https://scholar.google.com/citations?user=GxNfAV0AAAAJ&hl=en'
github: 'https://github.com/adaezy'
